export const Colors = {
  light: {
    background: "#f8f9fa",
    card: "#ffffff",
    text: "#212529",
    border: "#dee2e6",
    primary: "#007bff",
    primaryText: "#ffffff",
    error: "#dc3545",
    placeholder: "#6c757d",
    inputBackground: "#f2f2f2",
    inputBorder: "#cccccc",
    surface: '#f5f5f5',
     headerBackground: '#ffffff',
    headerText: '#000000',
    headerBorder: '#e5e5e5',
    statusBar: '#ffffff',
    statusBarContent: 'dark',
  },
  dark: {
    background: "#121212",
    card: "#1e1e1e",
    text: "#ffffff",
    border: "#333",
    primary: "#0d6efd",
    primaryText: "#ffffff",
    error: "#ff4d4f",
    placeholder: "#aaaaaa",
    inputBackground: "#1c1c1e",
    inputBorder: "#3a3a3c",
    surface: '#1e1e1e',
     headerBackground: '#1a1a1a',
    headerText: '#ffffff',
    headerBorder: '#333333',
    statusBar: '#121212',
    statusBarContent: 'light-content',
  },
};
